from __future__ import annotations

import json

from wpycli import Command, ConfigSettings, LoggingSettings

from .database import initialize_database

APP_NAME = "office_docs_mcp"


def build_root() -> Command:
    root = Command(
        use="office-docs-mcp",
        short="CLI template generated by wpygen",
        long="wpycli, wpyconf, wpylog 조합이 기본 구성된 CLI 템플릿입니다.",
        version="0.1.0",
    )
    root.add_persistent_string_flag("config", help="추가 config.toml 경로", shorthand="c")
    root.add_persistent_string_flag("dotenv", help="추가 .env 경로")
    root.add_persistent_string_flag("log-level", help="로그 레벨 override")
    root.add_persistent_string_flag("log-file", help="로그 파일 경로 override")
    root.configure_runtime(
        config=ConfigSettings(
            defaults={
                "app": {
                    "name": APP_NAME,
                    "default_target": "world",
                    "grpc_enabled": False,
                },
                "logging": {"level": "INFO", "file": None},
                "sqlite": {
                    "enabled": True,
                    "path": "data/office_docs_mcp.db",
                },
            },
            files=("config.toml",),
            dotenv=".env",
            env_prefix="OFFICE_DOCS_MCP",
            file_flag="config",
            dotenv_flag="dotenv",
        ),
        logging=LoggingSettings(
            logger_name="office_docs_mcp",
            level_flag="log-level",
            log_file_flag="log-file",
        ),
    )

    hello = Command(use="hello [name]", short="인사 메시지를 출력한다.", run=run_hello)
    hello.add_bool_flag("loud", help="대문자로 출력한다.", shorthand="l")
    config = Command(use="config", short="현재 설정을 출력한다.", run=run_config)
    db_init = Command(use="db-init", short="SQLite 파일과 기본 테이블을 준비한다.", run=run_db_init)
    serve = Command(
        use="serve", short="Start the Office Docs MCP server (Stdio transport).", run=run_serve
    )
    serve.add_string_flag(
        "transport", help="Transport type ('stdio' or 'sse')", default="stdio", shorthand="t"
    )
    root.add_command(hello, config, db_init, serve)
    return root


def run_hello(ctx):
    target = ctx.args[0] if ctx.args else str(ctx.config.get("app.default_target", "world"))
    if ctx.flags.get("loud"):
        target = target.upper()

    if ctx.logger is not None:
        ctx.logger.info("hello command invoked", extra={"target": target})

    body = f"{ctx.config.get('app.name', APP_NAME)} says hello to {target}."
    print(ctx.terminal.message("success", "Hello", body))
    return 0


def run_config(ctx):
    rendered = json.dumps(ctx.config.as_dict(), indent=2, sort_keys=True)
    print(ctx.terminal.pretty_json(rendered))
    return 0


def run_db_init(ctx):
    database_path = initialize_database(
        str(ctx.config.get("sqlite.path", "data/office_docs_mcp.db"))
    )
    if ctx.logger is not None:
        ctx.logger.info("sqlite initialized", extra={"path": str(database_path)})
    print(ctx.terminal.message("success", "SQLite", f"Database ready at {database_path}"))
    return 0


def run_serve(ctx):
    from .server import get_server

    transport = ctx.flags.get("transport", "stdio")
    server = get_server()
    if ctx.logger is not None:
        ctx.logger.info("Starting MCP server", extra={"transport": transport})
    server.run(transport=transport)
    return 0


def main() -> int:
    return build_root().execute()


if __name__ == "__main__":
    raise SystemExit(main())
